#!/usr/bin/env bash
echo " Automator for MiCloud Telepo   version 0.0.4 \n Copyright (c) 2017 Abhishek Kumar (kumarab@hcl.com), HCL Tech \n"
Source="/Users/kumarab/Documents/Workshop/Git/micloud"
Destination="/Users/kumarab/Documents/Workshop/Telepo"
if [[ "$1" == "" ]]; then 
    echo " Command missing! \n"
  else 
    cd $ROOT_DIR
	case "$1" in
    '-copy')
        echo " Copying new repository"
        cp -R "$Source/" "$Destination/"
        echo " Done! \n"
    ;;
    '-sync')
        echo " Syncing the repository"
        rsync -av "$Source/" "$Destination/" --exclude=".*"
        echo " Done! \n"
    ;;
    '-rsync')
        echo " Reverse syncing the repository"
        rsync -av "$Destination/" "$Source/" --exclude=".*"
        echo " Done! \n"
    ;;
    '-help')
        echo "\n Options:\n"
        echo "  -help       to see the menu of command line options"
        echo "  -setup      to set up environment"
        echo "  -copy       to copy new repository" 
        echo "  -sync       to sync existing repository"
        echo "  -rsync      to reverse sync existing repository"
        echo "  -merge      to merge existing repository"
        echo "  -diffsync   to merge the source changes into destination directory"
        echo "  -diff       to get changes made in single commit"
        echo "  -diffs      to get changes made in range of commits"
        echo "\n Usage:\n"
        echo "  automator -setup"
        echo "  automator -copy component-template"
        echo "  automator -sync component-template"
        echo "  automator -rsync component-template"
        echo "  automator -merge component-template"
        echo "  automator -merge component-template -preview"
        echo "  automator -diff component-template"
        echo "  automator -diffs component-template"
        echo "  automator -help"
        echo "\n Done! \n"
    ;;
    esac
fi
exit 0